version: '3'


services:

  #前端网关nginx-gateay (只代理laravel-in-docker-api)
  nginx-gateway:
    image: registry.cn-hangzhou.aliyuncs.com/u_ta_other/nginx:1.21.5
    container_name: nginx-gateway
    restart: always
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 8899:8081
    volumes:
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/log:/var/log/nginx
    networks:
      - laravel-in-docker-net
    depends_on:
      - laravel-in-docker-api

  #前端 API  php artisan config:clear
  laravel-in-docker-api:
    image: registry.cn-hangzhou.aliyuncs.com/u_ta_other/php-fpm:8.2-prod
    container_name: laravel-in-docker-api
    environment:
      # 时区上海 - Timezone Shanghai
      TZ: Asia/Shanghai
    volumes:
      - .:/var/www/html/laravel-in-docker:rw
      - ./storage/supervisor/api:/etc/supervisor/conf.d
    privileged: true
    restart: always
    networks:
      - laravel-in-docker-net

  #crontab 定时任务
  laravel-in-docker-cron:
    image: registry.cn-hangzhou.aliyuncs.com/u_ta_other/php-fpm:8.2-prod
    container_name: laravel-in-docker-cron
    environment:
      # 时区上海 - Timezone Shanghai
      TZ: Asia/Shanghai
    volumes:
      - .:/var/www/html/laravel-in-docker:rw
      - ./storage/supervisor/cron:/etc/supervisor/conf.d
    privileged: true
    restart: always
    networks:
      - laravel-in-docker-net

  #queue异步队列
  laravel-in-docker-queue:
    image: registry.cn-hangzhou.aliyuncs.com/u_ta_other/php-fpm:8.2-prod
    container_name: laravel-in-docker-queue
    environment:
      # 时区上海 - Timezone Shanghai
      TZ: Asia/Shanghai
    volumes:
      - .:/var/www/html/laravel-in-docker:rw
      - ./storage/supervisor/queue:/etc/supervisor/conf.d
    privileged: true
    restart: always
    networks:
      - laravel-in-docker-net


networks:
  laravel-in-docker-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

