#接口和定时任务镜像
FROM registry.cn-hangzhou.aliyuncs.com/u_ta_other/php-fpm:8.2-prod

WORKDIR /var/www/html/laravel-in-docker


#COPY composer*.json ./
#将Jenkins:laravel-in-docker项目下所有文件拷贝到WORKDIR(因为docker build是在Jenkins:laravel-in-docker项目目录下执行的)
COPY . .

COPY ./storage/supervisor/cron/*.conf ../../../../etc/supervisor/conf.d/

#ENTRYPOINT ["supervisorctl","reload"]

EXPOSE 9000







